spring:
  jpa:
#    ddl-auto: create-drop
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017

application:
  jwt:
    secret: somerandomshi*tthatchangesandsomeshitdontwork
    tokenPrefix: "Bearer "
    tokenExpirationAfterHours: 4


logging:
  level:
    web: debug